name: Flutter Web CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      # -----------------------------------------------------------------
      # 使用 subosito/flutter-action 锁定版本 3.35.7
      # -----------------------------------------------------------------
      - name: Setup Flutter (Version 3.35.7)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7"

      - name: Install Dependencies
        run: |
          # 确保 web 启用
          flutter config --enable-web
          flutter pub get

      - name: Build Web
        run: flutter build web --base-href /hao12345/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: web  # default: gh-pages
